### ISSUE TITLE
MDX dependencies are seriously outdated.

### ISSUE THREAD

**Issue by loke-dev** [renvrant/gatsby-mdx-netlify-cms#5]
`gatsby-mdx` has been deprecated, see: https://www.npmjs.com/package/gatsby-mdx

`@mdx-js/runtime` is being warned against being used as it increases bundle size and overhead, see: https://www.npmjs.com/package/@mdx-js/runtime

**Comment by renvrant** [comment]
Thanks for pointing this out.

MDX Runtime shouldn't be a concern given that this is statically generated, but other dependencies will need to be updated.
